name: Docker Deploy

on:
  workflow_run:
    workflows: 
      - ".NET 8 CI"
      - ".NET 9 CD (Entrega Contínua)"
    types:
      - completed

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Baixar artefato do build
      - name: Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: app-build       
          path: out/

      # Setup Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Login no Docker Hub
      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t julionavarroj/SistemaSalaoBeleza:latest .

      # Push da imagem Docker
      - name: Push Docker image
        run: docker push julionavarroj/SistemaSalaoBeleza:latest

      # Deploy remoto via SSH
      - name: Deploy remoto via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.
